services:
  db:
    image: bitnami/postgresql
    container_name: template_python_backend_db
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=template_python_backend
    ports:
      - "5432:5432"
    volumes:
      - db_data:/bitnami/postgresql


volumes:
  db_data:
