services:
  db:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=db_sge
    ports:
      - "5432:5432"
    volumes:
      - db_data:/bitnami/postgresql


volumes:
  db_data:
