"""init

Revision ID: 024a8465a709
Revises:
Create Date: 2025-06-16 11:47:05.220425

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024a8465a709'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tb_users',
        sa.Column('email', sa.String(length=200), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('first_name', sa.String(length=80), nullable=False),
        sa.Column('last_name', sa.String(length=80), nullable=False),
        sa.Column('phone', sa.String(length=15), nullable=True),
        sa.Column(
            'is_active',
            sa.Boolean(),
            server_default=sa.text('TRUE'),
            nullable=False,
        ),
        sa.Column(
            'id',
            sa.Uuid(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('tb_users_pkey')),
        sa.UniqueConstraint('email', name=op.f('tb_users_email_key')),
        sa.UniqueConstraint('id', name=op.f('tb_users_id_key')),
        sa.UniqueConstraint('phone', name=op.f('tb_users_phone_key')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_users')
    # ### end Alembic commands ###
